# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: wiz@1
  inputs:
    serviceConnectionId: 'Wiz'
    command: 'scan'
    scanType: 'dir'
    path: '.'
    succeedOnFailures: false
    policies: 'vuln-one-medium'
